export ALB_VIP="${APP_ENDPOINT}"
export REACT_APP_API_URL="${APP_ENDPOINT}"
export K8S_MASTER_IP="${K8S_MASTER_IP}"
export K8S_API_ENDPOINT="http://${K8S_MASTER_IP}:30080"
export NODE_ENV="production"
export DEPLOY_VERSION="terraform_init"

cat > /tmp/web-env <<EOF
ALB_VIP=${APP_ENDPOINT}
REACT_APP_API_URL=${APP_ENDPOINT}
K8S_MASTER_IP=${K8S_MASTER_IP}
K8S_API_ENDPOINT=http://${K8S_MASTER_IP}:30080
NODE_ENV=production
DEPLOY_VERSION=terraform_init
EOF
